s = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(s))
print('Só tem espaço?', s.isspace())
print('Só tem número?', s.isnumeric())
print('É alfabetico?', s.isalpha())
print('É alphanumérico?', s.isalnum())
print('Esta em maiúsculo? ', s.isupper())
print('Está em minúsculo?', s.islower())
print('Está capitalizado?', s.istitle())
